spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource: # H2 DB ??
    url: jdbc:h2:mem:webdemo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 DB ??? ????? ?? (http://localhost:8080/h2-console)
  jpa:
    database: H2
    show-sql: true # Jpa ?? ? SQL? ?? ??
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # ?? ??? ?? ????? ??
        # use-new-id-generator-mappings: false
    defer-datasource-initialization: true # ??? ??? ????, data.sql? ???? ???? ??